services:
  minio:
    image: "quay.io/minio/minio"
    ports:
      - "127.0.0.1:9900:9000"
      - "127.0.0.1:9901:9001"
    command: [ "server", "--console-address", ":9001", "/data" ]
    volumes:
      - "./minio:/data"
    environment:
      MINIO_ROOT_USER: minioAccessKey
      MINIO_ROOT_PASSWORD: minioSecretKey

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioAccessKey minioSecretKey;
      /usr/bin/mc anonymous set public myminio/foodies-nextjs;
      exit 0;
      "
